### ISSUE TITLE
frontend errors/http404?aspxerrorpath=xxx

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#104]
I according to the instructions of the document http://docs.virtocommerce.com/display/vc2devguide/Deploy+Elasticsearch+to+dedicated+server
config the website.

The backend can be successfully  accessed ,
the frontend homepage can be successfully   accessed,
but when I click the navigation menu ,url return the value "errors/http404?aspxerrorpath=xxx"
what else I need to do?

![1](https://cloud.githubusercontent.com/assets/5348170/10557115/5891ebe4-74d0-11e5-9e9c-0d3e04bc3c1e.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/10557117/76d9a16e-74d0-11e5-8e7d-7d8dcb36dc85.png)

**Comment by six006** [comment]
I found the solution to the problem.
Just config the store url
![1](https://cloud.githubusercontent.com/assets/5348170/10571957/70acab9a-7676-11e5-84e1-b52b181dae20.jpg)
![2](https://cloud.githubusercontent.com/assets/5348170/10571958/7158d186-7676-11e5-856d-c5edb3f548cb.png)

**Comment by Woland2k** [comment]
Glad you found a solution. It might be because default language was not set or is different for category you trying to open. For example you have SEO keyword set to "headphones" for en-us, but have no setting for zh-CN and thus when you first open the store it sets the default language to zh-CN and then tries to open URL using en-us keyword and thus not being able to find the category.

**Comment by IT4Solution** [comment]
Hi, guys. I am still with the same issue. No matter how I set up the store Url.
Am I missing something? Thank you


![admin](https://cloud.githubusercontent.com/assets/10602250/11020454/df66609a-8606-11e5-8e06-fb0364ee7c12.png)
![notfound](https://cloud.githubusercontent.com/assets/10602250/11020456/df6ebf56-8606-11e5-8fa3-8a64b6ad03af.png)
![root](https://cloud.githubusercontent.com/assets/10602250/11020455/df67b1ca-8606-11e5-9b6a-a26e7f287990.png)

**Comment by qq550723504** [comment]
I am still with the same issue. No matter how I set up the store Url.
Am I missing something? Thank you

**Comment by Wusifan** [comment]
hi,I have some problem about ElasticSearchQueryBuilder,and how can I builde a query string like blew when use ElasticSearchQueryBuilder  virto supplied.

    "query": {
        "bool": 
        { "must": [ { 
                "range": 
                { "startdate": { "to": "2015-12-02T13:00:05" } } },
                    {"wildcard" : { "catalog" : "vc-webshop" } } 
                ]

                ,"should": [ 
                    { "wildcard": { "HFDAUT_VOORL": { "value": "*ap*" } } },
                    { "wildcard": { "HFDAUT_ANAAM": { "value": "*ap*" } } },
                    { "wildcard": { "COMMERCIELE_TITEL": { "value": "*ap*" } } }
                    ]
                        } }

and in the must,we have two condition together,but when I use virto supply's function ElasticSearchQueryBuilder.cs ,it's just generated like as flows:

{ "bool": { "must": [ { "range": { "startdate": { "to": "2015-12-03T01:40:24" } } } ],"must": [ { "term": { "__hidden": { "value": "false" } } } ],"must": [ { "bool": { "should": [ {"wildcard" : { "__hidden" : "false" }} ] } } ],"must": [ { "bool": { "should": [ {"wildcard" : { "Catalog" : "VC-Webshop" }} ] } } ],"should": [ { "wildcard": { "HFDAUT_VOORL": { "value": "*ap*" } } },{ "wildcard": { "HFDAUT_ANAAM": { "value": "*ap*" } } },{ "wildcard": { "COMMERCIELE_TITEL": { "value": "*ap*" } } } ] } }

It's generate multi must santax and that it's not   comply with rules of es's  grammar.

can you give me som help?

**Comment by tatarincev** [comment]
@Wusifan  can you create new issue with you ES problem? 

@IT4Solution,  please excuse me for such a late response, but current storefront  implementation a was making faster as prototype and have a lot of bugs withch we cannot fast fix and hards to support. 

We deside to remake storefront implementation and almost finish it, you can get it from https://github.com/VirtoCommerce/vc-community/tree/dev-storefront  branch it will contains initially one base (liquid electronic - Thimber) theme but we try to migrate also Matherial theme if will have enought time.
 Below short list of new storefront key features
* New **Clear** storefront code arhitecture and theme development process
* angularjs checkout, user cabinet and product detail views
* support both liquid and razor view engines
* full Shopify themes compatible
* full page caching and incredible perfomance
* loading js and css resources  from CDN and cloudfare css 
* Reviews, product comparison, prmotions and more more..

And I notice that old implementation obsoleted and will be removed from next release
I recommend to not use current storefront implementation for you project and start examine or using   new.

We really want to make a quality product, in order to enable you to realize your projects quickly and without problems like these.
Thanks for undrestanding.

**Comment by haroldruss** [comment]
Hello, Tatarincev and VirtoCommerce Team. Thank you very much.

**Comment by IT4Solution** [comment]
Hello, Tatarincev and VirtoCommerce Team. Thank you very much.
