### ISSUE TITLE
How to develop a theme?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#127]
http://docs.virtocommerce.com/display/vc2devguide/Theme+Development

I  Edit theme using admin tool by going to "Browse->Content->Edit CSS/HTML", I want to build a theme,how to do it?

**Comment by tatarincev** [comment]
If you modified a theme in manager UI, your changes would be stored in DB and synchronized with storefront file system.
I suggest you to use storefront file system (AppData/themes/store-name) for theme development process as it allows viewing your changes on UI quickly. And use comfortable IDE (e.g. Visual studio editor) for themes editing; also you could use an appropriate source control system for changes history.
In order to update staging or production storefront theme, you need to zip the dev theme and upload it to server through Content/Theme upload. Current UI theme editor in manager isn’t convenient for serious theme development process and it should be used for small fixes or remarks only.
P.S
We are still working on themes engine and themes development process; they will be changed soon. Also we will write more clear documentation and how-tos.

**Comment by six006** [comment]
thanks ,I learn much from http://virtocommerce.github.io/Timber/
