### ISSUE TITLE
security users and roles 

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-community#132]
I use virtocommerce demo to test the user,role and permission.
1:assign role  "Electronic store administrator"  permissions :
catalog:access,
catalog:create
catalog:export
catalog:import	
catalog:read(Assigned scopes:Only for selected catalogs Electronics virtual and Electronics)
catalog:update(Assigned scopes:Only for selected catalogs Electronics virtual and Electronics)'

![1](https://cloud.githubusercontent.com/assets/5348170/11141707/d1053498-8a22-11e5-91de-35ccb6e9a2ec.jpg)

2:assign "demo"  as "Electronic store administrator" role
![2](https://cloud.githubusercontent.com/assets/5348170/11141719/f5cffb5a-8a22-11e5-97a2-8974966d84c2.jpg)

3:Login the admin panel use account "demo"
![3](https://cloud.githubusercontent.com/assets/5348170/11141753/3735aafe-8a23-11e5-92d6-f06046096d66.jpg)

4:Add a Catalogs "Just a Demo Test Catalog",save result is "Error401",I can delete it,but I can't manage it,refresh can't find it!
![4](https://cloud.githubusercontent.com/assets/5348170/11141798/95a82580-8a23-11e5-99e2-23a336347b4f.jpg)

5.Login the admin panel user account "admin",I can found the Catalog "Just a Demo Test Catalog"
![5](https://cloud.githubusercontent.com/assets/5348170/11141851/0b1ef154-8a24-11e5-9092-2fadad9c7fe6.jpg)

I suggest add some more permission on catalog ,for example 
category:access
category:create
category:delete
category:export
category:import
category:read
category:update

product:access
product:create
product:delete
product:export
product:import
product:read
product:update

**Comment by tatarincev** [comment]
Hi,  you have permission  to create catalogs but have limited read permission by two catalogs,of course you will get problems with new catalogs because you dont have permissions to read  it. Resonable will be next catalog:read permission assignment
**catalog:read : scope: created by me catalogs** but we currently not have this scope type, but it easy may be added. How to add it described here http://docs.virtocommerce.com/display/vc2devguide/Working+with+platform+security

Regarding your suggestion, our platform positioned as base for construction end solutions, which  may have many special requirements and complex busines scenarious. If we will include  each it our plaform fast become complex and overloaded by extra functions. I think many cases will be resolved by basic catalog permissions set, for more complex we always can extend it for concrete solution.
