### ISSUE TITLE
Reports - order pdf using ssrs

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-community#204]
Hi @tatarincev, @Woland2k,

Please see attached, my first version of order pdf. I have used SSRS as recommended by @Woland2k.

Can you please review this and advise if you want to add/remove anything. If everything looks ok than I am going to integrate this in the backend.

My integration plan is :-
1. Create some basic reports using SSRS to generate pdfs as I mentioned in #169.
2. Add new reporting module called "REPORTS" just like orders and stores etc.
3. Display list of reports avilable in the system.
4. Allow user to select and execute a report. This would be a generic report execution panel.
5. Expose a service which allow other modules to generate pdf or render report html using report viewer control.
6. Add print button on blade bar to print document. 
7. Connect print button with reports module to generate pdf.

Ofcouse i am going to keep all of these changes in my fork only. But if you find it useful I am more than happy to create pull requests.

[OrderReport (1).pdf](https://github.com/VirtoCommerce/vc-community/files/71936/OrderReport.1.pdf)

**Comment by Woland2k** [comment]
The report looks great. Creating reports module is also correct. I would create a way to categorize reports as well with simple categories/folders which then contain individual reports (similar UI to assets). Reports (templates) themselves should be saved using standard assets functionality (so they are for instance can be persisted in azure blob storage). Don't think any database functionality will be required for the module.

The standard reports can then be linked from order detail page to render selected order using report viewer.

Thanks again for contributing!

**Comment by tatarincev** [comment]
Hi @anwaramoon  report looks really great! But me really hard suggest something because I not familiar with SSRS service but I try to formulate some generic report module functional requirements:
* Full report management should be only on SSRS service not in VC Manager. (I think probably report module doesn not need any UI related to reports)
* It should expose some service  (code and API)  allows to other modules generate reports by name and special parameters and return download link with resulting report. 
* It should have some settings allow to configure connection to SSRS service.
* UI integration in other modules should be very simple (just adding button on toolbar with open wizard collected parameters for future report and download resulting report). Maybe report module can be exposed some special UI controls for input report parameters wizard.

Really thanks for you help!

**Comment by anwaramoon** [comment]
Thanks guys for your feedback. I'll let you know once integration is finished.
