### ISSUE TITLE
Docs: New module guide not up-to-date

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#243]
The Unmanaged module guide is not up-to-date as of VC2.6.

I tried to produce an unmanaged module(pure javascript) using the guide:
http://docs.virtocommerce.com/display/vc2devguide/Creating+new+module

The following adjustments are needed to get a workable unmanaged menu item with blade:

In the module.manifest remove the VirtoCommerce.Core dependency:
````
<dependency id="VirtoCommerce.Core" version="1.0.0" />
````

In the UnmanagedModule.js(Angular module) in the .run, provide a action property in the menuItem, which in his turn needs an injected state:
````
.run(
  ['platformWebApp.mainMenuService', '$state', function (mainMenuService, $state) {
      var menuItem = {
          path: 'browse/assets',
          icon: 'fa fa-folder-o',
          title: 'platform.menu.assets',
          priority: 130,
          action: function () { $state.go('workspace.assets'); },
          permission: 'platform:asset:access'
      };
      mainMenuService.addMenuItem(menuItem);
  }]);
````

Maybe other things needs to be refactored(minimize/maximize doesn't work on the blade) but now my newly module appears in the menu and actually works when being clicked on:

![image](https://cloud.githubusercontent.com/assets/1164988/12483896/bf90520e-c057-11e5-91a8-4780f7f61602.png)

![image](https://cloud.githubusercontent.com/assets/1164988/12483878/a28ac536-c057-11e5-89ff-5f225dac54e0.png)

Couple of other remarks on the fly so I won't flood the issues ;)

1) What are the requirements for unmanaged modules being deployed when using the deploy.cmd? My unmanaged module resides in the 
````
\PLATFORM\Modules\UnmanagedModule
````
folder but aren't deployed to the admin-modules artifacts folder(\artifacts\wwwroot\admin\Modules\) when running the deploy.cmd.

2) The artifacts folder itself isn't cleaned up before the deploy output files, so when some files are removed in the solution they are still in the artifacts folder after a re-run of the deploy.cmd

3) Maybe separate deploy scripts are handy, one for each solution(Manager, Platform, Store) and combinations of those: Platform only, Manager + Store, etc.

I just wanted to build a VC Platform release, no additional modules, no store front. So I had to change the deploy.cmd to build the VirtoCommerce.Platform.sln and not the VirtoCommerce.Manager.sln

No biggies but some nice polish :)

BTW, the build(deploy.cmd) is done in a heartbeat, nice!

**Comment by jvdonk** [comment]
Don't forget to inject the $state ;-)

The docs are updated(40 min ago) and the action property is added but the injected $state(in the angular.run section) is missing so this still won't work.

**Comment by jvdonk** [comment]
Found out the issue with the VirtoCommerce.Core dependency(in the module.manifest file)

It's a (core)module :) Which I didn't include in my Platform build so it wasn't there.

**Comment by artem-dudarev** [comment]
Hi @jvdonk, thanks for you post.

Indeed, the dependency on VirtoCommerce.Core is not required anymore. But it still can be used to mantain the order of modules during the initialization.
We have updated the documentation.

As for your other questions:

1) deploy.cmd compiles solutions/projects and copies the output to artifacts directory. Since unmanaged module is not a project it will not be deployed with deploy.cmd. Currently unmanaged modules should be packed manually.

2) It's not required to clean up the artifacts directory because the build output is being synchronized with artifacts using the KuduSync, which should detect deleted files and remove them from artifacts. I've just tested this case and can confirm that KuduSync removes the files which were removed from projects. Anyway you can just delete the artifacts directory before running the deploy.cmd

3) Separate deployment scripts sounds really good. We'll consider this in the future releases.
