### ISSUE TITLE
User of type Customer is allowed to login in admin

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-community#246]
As an SiteAdministrator I created a user of type Customer.

This user is able to login into the admin area, is there some functionality for customers available in the admin area?

When viewing notifications when logged in as this Customer-user, the system throws a 401 error so either this component should be disabled or not visible, same for notification settings or Journal of sending.

**Comment by tatarincev** [comment]
I try to explain why its happened now. VCF security system working only with security accounts and not use any information of account type (Administrator, Manager, Customer etc) even you can customize and extend to new customer types and its information not be used in security checks. That's why you can login within customer account to manager.     

But anyway you right, users with type Customers should unable to login in admin and we probably add this hard-coded constrain. Thanks @jvdonk.
