### ISSUE TITLE
Check working storefront on web farms

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-community#359]
Edit theme through Manager for case when storefront worked  on multiple farm macnihes
Check  with redis cache

**Comment by artem-dudarev** [comment]
1. Theme editing requires modification to storefront. It should use an abstraction layer instead of bare file system when working with theme files.
2. Distributed cache requires all cached objects to be serializable and deserializable. Currently there are errors when deserializing such objects as QuoteRequestTotals and ContentItem.

**Comment by artem-dudarev** [comment]
Fixed deserialization of QuoteRequest, Money, Currency and abstract classes.

**Comment by artem-dudarev** [comment]
Added distributed cache manager to storefront.

**Comment by artem-dudarev** [comment]
Added document describing recommended production configuration for Azure.
https://docs.google.com/document/d/1T6zqQKxfSzrfPH6y8c00gkWalIUpYgO7h2btkaJs7wo
