### ISSUE TITLE
What is the best way to do the query cross CustomerRepository and OrderRepository

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-community#43]
Current due to it's in the two separate DbContext, we could not use join easily :(

**Comment by tatarincev** [comment]
Is because we position our standart modules as isolated and each of it can be overriden to different implementation (for example *Customer module may be overriden to Google contacts serice*, *Order module to Shipstation service*) or uninstalled.
But if you want use same dbcontext for both modules you can write you new repository implementation (**ICustomerRepository, ICustomerOrderReoosutory**) used by one db context and  within that implementation you can make easy joins  queries. and injects your repository implementation to IoC container.

**Comment by zhangpeng-kooboo** [comment]
Thks @tatarincev , it make senses :+1:
And is there any reason in 2.x of VirtoCommerce try to split data model and domain model, currently most of them look same.
