### ISSUE TITLE
Can't uninstall module in 2.11 in azure deployment

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-community#504]
This is the error I receive:

```
Starting uninstall...
Uninstalling 'VirtoCommerce.Quote 2.11.0'
Deleting module D:\home\site\admin\Modules\VirtoCommerce.Quote folder
System.IO.IOException: Access to the path 'D:\home\site\admin\Modules\VirtoCommerce.Quote' is denied.
 at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
 at ChinhDo.Transactions.DeleteDirectoryOperation.MoveDirectory(String sourcePath, String destinationPath)
 at ChinhDo.Transactions.DeleteDirectoryOperation.Execute()
 at ChinhDo.Transactions.TxFileManager.EnlistOperation(IRollbackableOperation operation)
 at VirtoCommerce.Platform.Web.Modularity.ModuleInstaller.Uninstall(IEnumerable`1 modules, IProgress`1 progress)
Rollback all changes...
Installation finished.
```

**Comment by farsh42** [comment]
Did you grant the right permissions to your admin directory? as stated in docs users should have read and execute permission and the exception says that you dont have the right access to the modules directory.

**Comment by attilah** [comment]
It is in azure. You're not playing with permissions there I think.

**Comment by farsh42** [comment]
yes,sry didn't notice that.

**Comment by tatarincev** [comment]
Main reason for this problem is  that modules folders **Scripts** and **Content** css used by ASP.NET Bundles and monitored by FCN (File Change Notification). And any change in this folder cause ASP.NET pool restart and lock module folder what make unavailable to Delete it  (This operation used for module uninstall operation). We found some solution http://stackoverflow.com/questions/18063640/delay-appdomain-recycle-on-folder-change  but it seem do not work on azure environment. So we will continue to search other solution.
