### ISSUE TITLE
ICommerceRepository missing?

### ISSUE THREAD

**Issue by markwedinger** [VirtoCommerce/vc-community#76]
Im receiving the following error upon downloading the master and trying to compile.

Error	9	Source file 'Repositories\IСommerceRepository.cs' could not be found	C:\virto\vc-community-master\PLATFORM\Modules\Core\VirtoCommerce.CoreModule.Data\CSC	VirtoCommerce.CoreModule.Data

**Comment by Woland2k** [comment]
What Visual Studio are you using? I just downloaded the latest zip from master, unpacked it and copied to the folder (outside of user folder) and then opened in VS.NET 2013 and everything compiled without any issues. The file you mentioned exists in that path.

![image](https://cloud.githubusercontent.com/assets/1566470/10256524/ace899f2-6906-11e5-9f9f-a741fa98843a.png)

Sometimes issues can be caused by windows security, you need to unblock zip file for instance after downloading.

![image](https://cloud.githubusercontent.com/assets/1566470/10256482/6785dcb2-6906-11e5-98dc-83349b8676ff.png)

There is also issues with solution being inside user folder, so I would move it somewhere else.

**Comment by markwedinger** [comment]
2013


Here is a snap….its in the zip but the name is off… should have sent this originally..

**Comment by Woland2k** [comment]
don't think the zip went through

**Comment by markwedinger** [comment]
![image](https://cloud.githubusercontent.com/assets/2480287/10257180/e305f8b4-6923-11e5-8404-e41d0d91f48e.png)

**Comment by Woland2k** [comment]
That is very odd. Somehow latter "C" got corrupted. Maybe it is entered in a different encoding. Does renaming the file to correct one fixes the issue?

Did you download using giithub pull or as a zip? If using zip, what did you use to unzip the file?

**Comment by Woland2k** [comment]
I renamed the files and updated the master. Should be working correctly now.
